version: "3.4"
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=mesaDevelopment
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
  test_db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=mesaTest
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules
    ports:
    - 3333:3333
    depends_on:
      - db
    env_file: 
      - .env